FROM python:3.9-slim

USER root

WORKDIR /app

COPY python/ /app/

RUN python3 -m pip install --no-cache-dir --user kafka-python faker && \
    chmod 755 /app/kafka_producer.py

ENV PYTHONPATH="${PYTHONPATH}:/root/.local/lib/python3.9/site-packages"

CMD ["python", "kafka_producer.py"]
